---
- include: quickstart.yml
- include: quickstart-extras-undercloud.yml
- include: quickstart-extras-overcloud-prep.yml
- include: quickstart-extras-overcloud.yml
- include: quickstart-extras-validate.yml


# Add the overcloud nodes to the generated inventory.
- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: yes
  vars:
      inventory: all
  roles:
    - tripleo-inventory
    - add-host-builder
